### ISSUE TITLE
Breaking changes in this project

### ISSUE THREAD

**Issue by ivantm** [airbnb/babel-preset-airbnb#22]
:wave: After upgrading from v 2.2.3 to v2.3.3 (the versions in between are not published on NPM), generators stopped being transpiled.

I would consider this to be a breaking change (e.g. if the resulting code after upgrading from 2.2.3 to 2.3.3 is passed to uglify, it will throw errors, IE11 will throw because it doesn't understand generators, etc). The issue is present in 2.4.0 too.

It would be useful to consumers if you could clarify what you consider to be breaking changes for this project so people know what semver ranges are safe to use (e.g. `^2.0.0` vs `~2.2.0` or `2.2.3`)

**Comment by ljharb** [comment]
Hmm - generators never should have been transpiled in the first place, since airbnb doesn't use them.

I'd consider it a bug that they were ever transpiled in the first place - this module is meant to be used in concert with `eslint-config-airbnb` or `eslint-config-airbnb-base`, which forbids syntax that we don't transpile.

Since you have a codebase to test it on, could you help determine what the first version was that transpiled generators?

**Comment by goatslacker** [comment]
v2.2.3 wasn't supposed to transpile generators which the [docs state here](https://github.com/airbnb/babel-preset-airbnb/blame/v2.2.3/README.md#L6).

**Comment by ivantm** [comment]
@ljharb Based on my tests, generator support was in `babel-preset-airbnb` from (at least) 2.0.0

@goatslacker wrote:

> v2.2.3 wasn't supposed to transpile generators which the docs state here.

The reason I see given in those docs is this:

> generators: `regenerator-runtime` is too heavyweight for our use

That's a good reason for dropping them - however, if you're taking a semver approach (I'm making an assumption here), then it's also a good reason for a major version bump. If this change had been released as 3.0.0, then everything would've continued working for people who had relied - for better or worse - on generators being transpiled between 2.0.0 - 2.2.3 and who had subscribed to a more liberal semver range (e.g. `^2.0.0).

**Comment by ljharb** [comment]
In this case, I'd say relying on that was always a bug - generator support wasn't part of the API, and as such, dropping it wasn't a breaking change.

**Comment by ivantm** [comment]
This comes down to how you define what the API for a project like this actually is (e.g. if this project had tests, some would assert that the language features you listed as excluded in the README were not transpiled).

I'd suggest that since generators were not listed as an exclusion in 2.0.0, then they were implicitly part of the API for v2.x and removing them later on should have been a breaking change. It felt like a breaking change to me because it broke the builds for one of the teams where I work and finding the root cause took quite some of time. However, given the lack of any other issues we may have been the only ones. 

Those are just some thoughts - the debate is probably bigger than this project and I don't want to waste your time if you disagree so I'm happy for this to be closed.

**Comment by ljharb** [comment]
Usually I'm on the side you're advocating for, to be honest - but in this case, our babel preset is meant to be paired with our eslint config and style guide, which strictly bans generators.
