### ISSUE TITLE
How to config it to support es2017?

### ISSUE THREAD

**Issue by linchen2chris** [airbnb/babel-preset-airbnb#26]

**Comment by ljharb** [comment]
It already does. Do you have a specific feature you're looking for?

**Comment by linchen2chris** [comment]
thanks @ljharb, actually I wanna use decorators, I install babel-plugin-transform-decorators-legacy and add it to .babelrc, it works now

**Comment by ljharb** [comment]
Decorators are stage 2, so they're not ES-anything right now. The transform you indicated is indeed the only way to use them at this time.
