### ISSUE TITLE
This repository is not compatible with "babel-cli": "7.0.0-beta.0" and "babel-preset-env": "^2.0.0-beta.0"

### ISSUE THREAD

**Issue by eaulav** [airbnb/babel-preset-airbnb#27]
We want to use the "browserslist" and configure this in package.json is from evilmartains:
https://github.com/ai/browserslist

This is supported in babel 7.0

**Comment by ljharb** [comment]
babel 7 is not out yet; if there’s nonbreaking changes we can make now to support the beta, we’ll consider them - otherwise we’re going to wait until it’s actually released.

**Comment by brammittendorff** [comment]
Thats a pitty we are waiting for these changes to... It is possible to use 7.0.0-beta but this repository is not supporting it. I really hope you consider to support the beta.

**Comment by ljharb** [comment]
Again, if there’s a way to support both, I’d be happy to review a PR, but it’s still a beta for a reason.

**Comment by dkrnl** [comment]
Babel 7 Released
https://babeljs.io/blog/2018/08/27/7.0.0

**Comment by ljharb** [comment]
Indeed; that was 2 days ago. If someone wants to put up a PR that makes this preset compatible with both babel 6 and 7 (if possible), or else put up one that switches to babel 7, that'd be great.

**Comment by davalapar** [comment]
Got one cooking up @ https://github.com/airbnb/babel-preset-airbnb/pull/37
