### ISSUE TITLE
webpack (3) return with UglifyJS error

### ISSUE THREAD

**Issue by blasterbug** [airbnb/babel-preset-airbnb#28]
When using `webpack` with options `-p` or plugin UglifyJsPlugin, I got this 
```
ERROR in someBundle.someHash.js from UglifyJs
Unexpected token: keyword (function) [someBundle.someHash.js:31983,14]
```
I have tried to update babel config with different presets and it work, I have that error when I only use `babel-preset-airbnb`. And I don't think using `babel-preset-es2015` or `babel-preset-env`  along side is a good solution.

**Comment by ljharb** [comment]
Can you provide the code that line and column point to?

**Comment by blasterbug** [comment]
```javascript
        async function componentDidMount() {
```
I guess `async` is the problem. I actually have the error two times and they point to the same code.

**Comment by ljharb** [comment]
Yes, that’s the problem. Our preset doesn’t transpile async functions (our guide currently forbids them) and uglify can’t handle ES6+ syntax.

You can either not use async await, or you can add a babel transform for them on top of this preset.
