### ISSUE TITLE
object rest/spread has been in ES9.

### ISSUE THREAD

**Issue by Aladdin-ADD** [airbnb/babel-preset-airbnb#34]
> We have also enabled object rest/spread, although it is only at stage 2. It will hopefully achieve stage 3 soon.

object rest/spread has been in ES9.

**Comment by ljharb** [comment]
ES2018 :-) and yes, we need to update the readme there, thanks.

**Comment by ljharb** [comment]
Closed with https://github.com/airbnb/babel-preset-airbnb/commit/60d2d919316481ae5a52d37cd111a71308483536
