### ISSUE TITLE
Add babel-plugin-transform-react-jsx-source

### ISSUE THREAD

**Issue by kesne** [airbnb/babel-preset-airbnb#4]
https://www.npmjs.com/package/babel-plugin-transform-react-jsx-source

**Comment by kesne** [comment]
https://twitter.com/dan_abramov/status/779308833399332864

**Comment by ljharb** [comment]
Sounds great - want to make a PR?

**Comment by goatslacker** [comment]
PR++ make sure it's run on dev only.

**Comment by ljharb** [comment]
This will be handled by #37.
