### ISSUE TITLE
ImportDeclaration / ExportDeclaration Conflict

### ISSUE THREAD

**Issue by mackenziemance** [airbnb/babel-preset-airbnb#40]
Problem is resolved if ImportDeclaration and ExportDeclaration options are removed.

**Atom Linter warning output**

Configuration for rule "object-curly-newline" is invalid: Value {"ObjectExpression":{"minProperties":4,"multiline":true,"consistent":true},"ObjectPattern":{"minProperties":4,"multiline":true,"consistent":true},"ImportDeclaration":{"minProperties":4,"multiline":true,"consistent":true},"ExportDeclaration":{"minProperties":4,"multiline":true,"consistent":true}} should be equal to one of the allowed values. Value {"ObjectExpression":{"minProperties":4,"multiline":true,"consistent":true},"ObjectPattern":{"minProperties":4,"multiline":true,"consistent":true},"ImportDeclaration":{"minProperties":4,"multiline":true,"consistent":true},"ExportDeclaration":{"minProperties":4,"multiline":true,"consistent":true}} should NOT have additional properties. Value {"ObjectExpression":{"minProperties":4,"multiline":true,"consistent":true},"ObjectPattern":{"minProperties":4,"multiline":true,"consistent":true},"ImportDeclaration":{"minProperties":4,"multiline":true,"consistent":true},"ExportDeclaration":{"minProperties":4,"multiline":true,"consistent":true}} should match exactly one schema in oneOf. Value {"ObjectExpression":{"minProperties":4,"multiline":true,"consistent":true},"ObjectPattern":{"minProperties":4,"multiline":true,"consistent":true},"ImportDeclaration":{"minProperties":4,"multiline":true,"consistent":true},"ExportDeclaration":{"minProperties":4,"multiline":true,"consistent":true}} should NOT have additional properties. Value {"ObjectExpression":{"minProperties":4,"multiline":true,"consistent":true},"ObjectPattern":{"minProperties":4,"multiline":true,"consistent":true},"ImportDeclaration":{"minProperties":4,"multiline":true,"consistent":true},"ExportDeclaration":{"minProperties":4,"multiline":true,"consistent":true}} should match exactly one schema in oneOf.

Referenced from: /Users/user/Documents/project/node_modules/eslint-config-airbnb-base/index.js

**Comment by ljharb** [comment]
What version of babel are you using? Does `npm ls` exit successfully?

**Comment by mackenziemance** [comment]
7 and yep. I rolled back a couple commits with no change in babel-preset-airbnb so It must be a conflict with another package.

**Comment by mackenziemance** [comment]
**Before**
  - .git
  - node_modules
  - .babelrc
  - .eslintrc


**After**
  - .git
    - project
       - node_modules
       - .babelrc
       - .eslintrc

**After(no error)**
  - .git
    - project
       - .babelrc
       - .eslintrc

**Comment by mackenziemance** [comment]
This is the strangest bug, any ideas ?
It's just those two options throwing the warning. Otherwise I'd be posting on stack.

**Before (no warning)**
  - .git
  - node_modules
  - .babelrc
  - .eslintrc

**After: target structure (warning)**
  - .git
    - project
       - node_modules
       - .babelrc
       - .eslintrc

**After (no warning)**
  - .git
  - node_modules
    - project
       - .babelrc
       - .eslintrc

**Comment by ljharb** [comment]
I’m a bit confused; why would you ever have node_modules not at the root?

**Comment by mackenziemance** [comment]
My bad, should’ve been more clear. I’m not, the third is just showing that the warning is suppressed in the After structure when node_modules is lifted. Target is what I’m going for.

**Comment by mackenziemance** [comment]
If you got nothing off the top feel free to close. It’s obviously an edge and I’ll just fork.

**Comment by ljharb** [comment]
I’m still a bit confused. node_modules should only ever be at the root - unless you have a package.json inside “project”.

However, I’m not sure why forking would be necessary. It’s not clear yet from your issue what tool is generating the error - if you’re using eslint in atom, what happens when you run eslint on the command line?

**Comment by mackenziemance** [comment]
It's Atom-linter, Things run fine in the CLI. I was mislead by the warning and that addressing it with
`sed -i ''  '398,399d' ~/Documents/repo/project/node_modules/eslint-config-airbnb-base/rules/style.js` 
would return things to normal. 

Apologies for issue and thanks for your help.
