### ISSUE TITLE
Usage with @babel/polyfill

### ISSUE THREAD

**Issue by MatteBailey** [airbnb/babel-preset-airbnb#41]
I would like to use `@babel/polyfill` along with this preset. The docs for `@babel/preset-env` talk about the [`useBuiltIns`](https://babeljs.io/docs/en/babel-preset-env#usebuiltins) option, which enables you to use `@babel/polyfill` in ways that prevent importing the entire polyfill. Is there any way to access `useBuiltIns` when using this preset?

Thanks!

**Comment by ljharb** [comment]
We recommend https://npmjs.com/airbnb-browser-shims over babel-polyfill.

In terms of the `useBuiltIns` option, we'd have to add an explicit passthrough for that.

**Comment by MatteBailey** [comment]
Got it! Adding a passthrough might make sense if others folks have the same use case as me, but probably not super high priority at the moment.
