### ISSUE TITLE
Missing transformations for Stage 3 syntax

### ISSUE THREAD

**Issue by MatteBailey** [airbnb/babel-preset-airbnb#42]
The README states that this preset contains transformation for all stage 3 syntax, but I noticed that [`@babel/plugin-proposal-class-properties`](https://babeljs.io/docs/en/next/babel-plugin-proposal-class-properties.html), for example, is not included here. Is this intentional, or has it just not been added yet?

Sorry for the second issue in one day, and thanks!

**Comment by ljharb** [comment]
This is intentional; we also use our shared eslint config, which uses eslint's default parser, which only supports stage 4 syntax.

When we support class fields in our style guide, we'll also support it here.

**Comment by MatteBailey** [comment]
That makes sense. This was the line that confused me:
> Currently contains transforms for all standard syntax that is stage 4 (ES2018) or stage 3, except for the following:

Is "standard syntax" the key part there, and why class fields are not supported? From reading that, it's not very clear to me what stage 3 features I can expect to be available.

**Comment by MatteBailey** [comment]
Addressed in #43.
