### ISSUE TITLE
"Parsing error: Unexpected token *" with v8.2.2 in Node 6

### ISSUE THREAD

**Issue by KamuelaFranco** [airbnb/babel-preset-airbnb#49]
I'm having a lint fail in CI using the Airbnb but only with Node 6. Some investigation yielded https://github.com/babel/babel-eslint/issues/605 and https://github.com/babel/babel/issues/7654.

Is it possible to force this dependency to use a different version of the babel suite while using `airbnb-base`? I'm not sure how to solve this otherwise, but completely open to all help and suggestions. Thank you.

**Comment by ljharb** [comment]
That seems to be a bug with a specific beta version of babel 7 - can you try with the actual, released version?

**Comment by KamuelaFranco** [comment]
How can I be sure of the final version in use? I don't depend on `babel` directly in my project, just what's recommended here: `npx install-peerdeps --dev eslint-config-airbnb-base`

**Comment by KamuelaFranco** [comment]
I'm going to close this because I can't seem to reproduce it anymore, and it might have to do with some caching or environment issues outside of my control. Will reopen if it comes back with any consistency. Thank you for the help.
