### ISSUE TITLE
BUG : Warning import with version 4.0.1

### ISSUE THREAD

**Issue by lpeliberty** [airbnb/babel-preset-airbnb#55]
Hello, I have an issue with the latest version of babel-preset-airbnb (v4.0.1) : When I compile with webpack I have this warning : 
```
WARNING in ./path/to/ItemFile.jsx 112:21-27
"export 'create' was not found in './path/to/react-doka-4.6.1/lib/doka.esm.min'
```
Here is how I import the function : 
```
import { create } from './path/to/react-doka-4.6.1/lib/doka.esm.min';
```

But in doka.esm.min I have an export :
```
...
exports.create = create;
```

This problem does not occurs with version 3.3.2. Is it normal ?

Thx for all.

**Comment by lpeliberty** [comment]
Still having this issue...

**Comment by ljharb** [comment]
`exports.create =` is not a named "create" export; that's just a "create" property on your CJS module's default export. Many tools, including babel, conflate named imports with destructuring - ie, it's doing `import blah from 'path'; const { create } = blah` for you.

I'm not sure where this warning is coming from, but I assume not from this preset - rather, from something in your build pipeline, which may not even be babel.

**Comment by lpeliberty** [comment]
Ok, I still get it. I stay in 3.3.2... Thx.
